### PR TITLE
Add ready-to-build docs folder with the mkdocs tool

### LINKED ISSUE #196: Create Github page for this project
It would be nice to have a Github page that contains the README information using a more readable layout, and also a mulang online tester based on the .js distribution. It should: 

* Allow you to enter a Mulang AST and run inspections over it
* Allow you to transform one of the supported languages and transform it to mulang
* Run other analyses

### PR DESCRIPTION
**Pull request by Javi**
Fixes #196 
In order to build the site for uploading (to GH pages for example) or serving locally, you need to run `mkdocs`, which is available from `brew`, `apt-get`, `choco` and others.

From then, `mkdocs serve` will host the site locally, and `mkdocs gh-deploy` compiles the site and pushes it to the gh-pages branch.

Currently the user guide looks like this:
untitled

And the first iteration of the analyser looks like this:
image

Some known things to improve on:
- Depend on mumuki-styles and the JSON viewer instead of having a drop-in
- Add a rich text editor to the spec textarea (maybe Ace?)
- Improve styles and copy
- A few small code refactors such as separating the analyser into another puse html file

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@Javi I couldn't start the server. I got the following: 

```
INFO    -  Building documentation... 
WARNING -  Config value: 'nav'. Warning: Unrecognised configuration name: nav 
ERROR   -  Config value: 'theme'. Error: Unrecognised theme. 

Aborted with 1 Configuration Errors!
```

**Comment by Javi** [comment]
Should be fixed now!

**Comment by flbulgarelli** [comment]
In addition to the improvements already mentioned, I'd add some kind of explanation and/or samples of what you can actually try. Perhaps a combo with a list of samples ready to be copied on the editor. 

Also, it would be nice to be able to have an additional simplified try-it for just coding a program and selecting the language, and generating the AST.

**Comment by flbulgarelli** [comment]
Also, we should stop copying `mulang.js` and instead deploying it as a npm package

**Comment by flbulgarelli** [comment]
> Depend on mumuki-styles and the JSON viewer instead of having a drop-in

I don't see any native npm/bower support for mkdocs at first glance. Perhaps we could have a `docs/devinit` like the following pseudo-bash-code:

```bash
echo "[Mulang::Docs] Cleaning up resources..."
rm docs/js/mulang.js
rm docs/js/mumuk-styles.js
rm docs/css/mumuki-styles.js

echo "[Mulang::Docs] Installing mulang.js..."
wget https://github.com/mumuki/mulang/releases/download/v4.2.0/mulang.js.zip | unzip > docs/js/mulang.js

echo "[Mulang::Docs] Installing mumuki-styles..."
wget https://raw.githubusercontent.com/mumuki/mumuki-styles/master/dist/css/mumuki-styles.css docs/css/mumuki-styles.css
wget https://raw.githubusercontent.com/mumuki/mumuki-styles/master/dist/javascripts/mumuki-styles.js docs/js/mumuki-styles.js

echo "[Mulang::Docs] Building the docs for first time..."
mkdocs build

echo "[Mulang::Docs] Done! Now run mkdocs serve"
```

**Comment by flbulgarelli** [comment]
> @flbulgarelli Is there a published npm version of Mulang?

yes! Check here https://www.npmjs.com/package/mulang

**Comment by flbulgarelli** [comment]
I have just pushed JS compiled version for 4.5.2. We should update this PR.

**Comment by flbulgarelli** [comment]
Also, we should put the docs in sync with current readme

**Comment by flbulgarelli** [comment]
I have just removed cinder from source control. We should do the same with json-viewer

**Comment by flbulgarelli** [comment]
Pending tasks:

- bug en position.sdasdsa
- agregar mas ejemplos en try
- mostrar ejemplos de EDL andando
- formatter de EDL
- shortcuts en js y rb
- i18n en rb
- documentar matchers
- document hackage removal

**Pull request merged**
