### PR TITLE
Moving rungs to gs-weblang-cli repository and updating to last version

### PR DESCRIPTION
**Pull request by rodri042**

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Hmm do you why is failling? Did it worked locally?

**Comment by rodri042** [comment]
@flbulgarelli The tests pass on my machine.  Its a weird dependency problem:
```
cabal: Error: some packages failed to install:
language-javascript-0.5.14.7 failed during the configure step. The exception
was:
ExitFailure 1
```

**Comment by flbulgarelli** [comment]
Please try hardcoding versions:

```
Configuring call-stack-0.1.0...
Configuring dlist-0.8.0.2...
Configuring containers-0.5.6.2...
Configuring bytestring-0.10.6.0...
Building call-stack-0.1.0...
Building dlist-0.8.0.2...
Building containers-0.5.6.2...
Building bytestring-0.10.6.0...
Configuring fail-4.9.0.0...
Installed dlist-0.8.0.2
Configuring random-1.1...
Installed call-stack-0.1.0
Building fail-4.9.0.0...
Building random-1.1...
Configuring split-0.2.3.1...
Installed fail-4.9.0.0
Building split-0.2.3.1...
Configuring syb-0.6...
Installed split-0.2.3.1
Building syb-0.6...
Configuring stm-2.4.4.1...
Installed random-1.1
Configuring transformers-0.5.2.0...
Installed syb-0.6
Building stm-2.4.4.1...
Building transformers-0.5.2.0...
Installed stm-2.4.4.1
Configuring HUnit-1.5.0.0...
Building HUnit-1.5.0.0...
Installed HUnit-1.5.0.0
Configuring haskell-src-1.0.2.0...
Building haskell-src-1.0.2.0...
Configuring async-2.1.0...
Installed bytestring-0.10.6.0
Building async-2.1.0...
Installed transformers-0.5.2.0
Configuring hspec-expectations-0.8.2...
Building hspec-expectations-0.8.2...
Configuring bytestring-builder-0.10.8.1.0...
Installed async-2.1.0
Building bytestring-builder-0.10.8.1.0...
Installed hspec-expectations-0.8.2
Configuring unix-2.7.2.0...
Installed bytestring-builder-0.10.8.1.0
Configuring utf8-string-1.0.1.1...
Building utf8-string-1.0.1.1...
Configuring mtl-2.2.1...
Installed utf8-string-1.0.1.1
Building mtl-2.2.1...
Configuring primitive-0.6.1.0...
Installed mtl-2.2.1
Building primitive-0.6.1.0...
Building unix-2.7.2.0...
Configuring transformers-compat-0.5.1.4...
Installed haskell-src-1.0.2.0
Building transformers-compat-0.5.1.4...
Installed containers-0.5.6.2
Configuring binary-0.8.4.1...
Configuring template-haskell-2.8.0.0...
Installed primitive-0.6.1.0
Installed transformers-compat-0.5.1.4
Building binary-0.8.4.1...
Configuring tf-random-0.5...
Building template-haskell-2.8.0.0...
Building tf-random-0.5...
Configuring vector-0.11.0.0...
Installed tf-random-0.5
Building vector-0.11.0.0...
Installed binary-0.8.4.1
Configuring text-1.2.2.1...
Building text-1.2.2.1...
Installed unix-2.7.2.0
Configuring ansi-terminal-0.6.2.3...
Building ansi-terminal-0.6.2.3...
Installed template-haskell-2.8.0.0
Configuring directory-1.2.7.0...
Building directory-1.2.7.0...
Configuring setenv-0.1.1.3...
Installed ansi-terminal-0.6.2.3
Building setenv-0.1.1.3...
Installed setenv-0.1.1.3
Configuring tagged-0.8.5...
Building tagged-0.8.5...
Installed directory-1.2.7.0
Configuring hspec-discover-2.3.2...
Building hspec-discover-2.3.2...
Installed tagged-0.8.5
Configuring process-1.3.0.0...
Installed hspec-discover-2.3.2
Building process-1.3.0.0...
Installed process-1.3.0.0
Installed text-1.2.2.1
Configuring blaze-builder-0.4.0.2...
Configuring hashable-1.2.4.0...
Configuring parsec-3.1.9...
Building blaze-builder-0.4.0.2...
Building parsec-3.1.9...
Building hashable-1.2.4.0...
Installed hashable-1.2.4.0
Configuring nats-1.1.1...
Building nats-1.1.1...
Configuring unordered-containers-0.2.7.1...
Installed vector-0.11.0.0
Configuring scientific-0.3.4.9...
Installed blaze-builder-0.4.0.2
Building unordered-containers-0.2.7.1...
Building scientific-0.3.4.9...
Installed nats-1.1.1
Configuring language-javascript-0.5.14.7...
Building language-javascript-0.5.14.7...
Installed parsec-3.1.9
Configuring ParsecTools-0.0.2.0...
Building ParsecTools-0.0.2.0...
Configuring inflections-0.2.0.1...
Installed ParsecTools-0.0.2.0
Building inflections-0.2.0.1...
Installed scientific-0.3.4.9
Installed inflections-0.2.0.1
Installed unordered-containers-0.2.7.1
Configuring semigroups-0.18.2...
Building semigroups-0.18.2...
Installed language-javascript-0.5.14.7
Installed semigroups-0.18.2
Configuring QuickCheck-2.9.2...
Configuring attoparsec-0.13.1.0...
Building QuickCheck-2.9.2...
Building attoparsec-0.13.1.0...
```

**Comment by rodri042** [comment]
@flbulgarelli still failing :(

**Comment by flbulgarelli** [comment]
@rodri042 yes, but error message is different now!

**Comment by flbulgarelli** [comment]
Actually, now `haskell-src`, which was previously failing, is being added properly. 

Now JS dependency is failing: 

```
Failed to install language-javascript-0.5.14.7
Last 10 lines of the build log ( /home/travis/.cabal/logs/language-javascript-0.5.14.7.log ):
Configuring language-javascript-0.5.14.7...
setup-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4: The program happy version >=1.19
is required but the version found at /usr/bin/happy is version 1.18.9
```

**Comment by rodri042** [comment]
That was the dependency that initially failed :/. See my first comment.

**Comment by flbulgarelli** [comment]
> That was the dependency that initially failed :/. See my first comment.

But it was because `haskell-src` was failing. Now it is failing for a different reason, which is apparently simpler to understand - the `happy` executable version is a bit old. We could try updating it - it should be a travis config - or downgrading dependencies to that version they had when master passed on travis - see last success master build logs.

**Pull request merged**
